using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI; //UIï¿½ÖŒWï¿½Ìˆ×‚Ìƒï¿½ï¿½Cï¿½uï¿½ï¿½ï¿½ï¿½
using UnityEngine.SceneManagement; //ï¿½ï¿½ï¿½[ï¿½hï¿½ÖŒWï¿½ï¿½Kï¿½vï¿½Èƒï¿½ï¿½Cï¿½uï¿½ï¿½ï¿½ï¿½

/// <summary>
/// systemï¿½\ï¿½ï¿½ï¿½Ì•Ïï¿½ï¿½Ğ‚Æ‚Ü‚Æ‚ß‚ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½ï¿½B
/// </summary>
[System.Serializable]
public struct SystemDataSet
{
    public GameObject startButton; //ï¿½Jï¿½nï¿½{ï¿½^ï¿½ï¿½
    public GameObject exitButton; //ï¿½Iï¿½ï¿½ï¿½{ï¿½^ï¿½ï¿½
    public Text startText; //ï¿½Jï¿½nï¿½{ï¿½^ï¿½ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½eï¿½Lï¿½Xï¿½g
    public string LodedName;

}

public class TitleManager : MonoBehaviour
{
    //ï¿½_ï¿½Åï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ö˜Aï¿½Ïï¿½
    float time;
    float speed = 0.3f;

    public SystemDataSet system; //ï¿½ï¿½ï¿½ÌéŒ¾

    //ï¿½Qï¿½[ï¿½ï¿½ï¿½ÌƒCï¿½ï¿½ï¿½[ï¿½Wï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Ìì¬
    [SerializeField] Transform player;
    Vector3 startPos;
    Vector3 moveVec;

    // Start is called before the first frame update
    void Start()
    {
        startPos = player.position; //ï¿½Åï¿½ï¿½ÌˆÊ’uï¿½Û‘ï¿½
        Debug.Log($"startPos = {startPos}");
    }

    public void StartButton()
    {
        SceneManager.LoadScene(system.LodedName);
    }

    public void ExitButton()
    {
        Application.Quit();
    }

    /// <summary>
    /// ï¿½_ï¿½Åï¿½ï¿½ï¿½ï¿½Öï¿½
    /// </summary>
    /// <param name="color"></param>
    /// <returns></returns>
    Color Text_Invicivil(Color color)
    {
        time += Time.deltaTime * 4.0f * speed; //ï¿½_ï¿½Å‚ï¿½ï¿½é‘¬ï¿½xï¿½İ’ï¿½
        color.a = Mathf.Sin(time); //ï¿½ï¿½ï¿½lï¿½ï¿½ÏXï¿½ï¿½ï¿½Ä“_ï¿½Åï¿½ï¿½ï¿½ï¿½ğ‘£‚ï¿½


        return color; //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É•Ô‚ï¿½
    }


    void ImageMove()
    {

        player.Translate(0.05f ,0,0);

        if (player.position.x >= 10.0f)
        {
            player.position = startPos;
        }
    }

    // Update is called once per frame
    void Update()
    {
        system.startText.color = Text_Invicivil(system.startText.color); //ï¿½Ô‚ï¿½ï¿½ï¿½ï¿½lï¿½É‘ï¿½ï¿½ï¿½ï¿½ï¿½Öï¿½ï¿½É“nï¿½ï¿½

    }

    private void FixedUpdate()
    {
        ImageMove();
    }
}
